CREATE TABLE ai_use_case_inventory_2026 (
    id varchar(10) NOT NULL PRIMARY KEY,
    name varchar(255) NOT NULL,
    bureau varchar(10) NOT NULL,
    email varchar(100) NOT NULL,
    stage_of_development char NOT NULL,
    high_impact char NOT NULL,
    justification varchar(2048) NULL
);

COPY ai_use_case_inventory_2026 (id, name, bureau, email, stage_of_development, high_impact, justification) FROM stdin;
DHS-172	Video Analysis Tool (VAT)	ICE	ai@hq.dhs.gov	d	a	\N
DHS-197	Mobile Language Translation Services	ICE	ai@hq.dhs.gov	d	a	\N
DHS-2409	ICE Mobile Check-in Application	ICE	ai@hq.dhs.gov	d	a	\N
DHS-414	I-765 - USCIS Face Capture Mobile App	USCIS	ai@hq.dhs.gov	d	a	\N
DHS-123	Voice Analytics for Investigative Data	ICE	ai@hq.dhs.gov	d	b	The definition states that the "output serves as a principal basis for a decision or action concerning a specific individual or entity..."  However, the output of the AI is never the only basis for a decision, and no rights impacting action is taken unless a human is in the loop making a further determatination
DHS-49	Mobile Device Analytics for Investigative Data	ICE	ai@hq.dhs.gov	d	b	The definition states that the "output serves as a principal basis for a decision or action concerning a specific individual or entity..."  However, the output of the AI is never the only basis for a decision, and no rights impacting action is taken unless a human is in the loop making a further determatination
DHS-57	Identity Match Option (IMO) Tool for Record Compilation	USCIS	ai@hq.dhs.gov	d	b	The use case compiles records from across a variety of USCIS systems to provide a comprehensive history of a person’s interaction with USCIS. The AI output can be visualized through a report or dashboard to assist with case review ensuring access to useful and accurate records. (SEE DHS CAIO SUPER MEMO FY24)   ------  The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.  The use case compiles records from across a variety of USCIS systems to provide a comprehensive history of a person’s interaction with USCIS. The output of this can be visualized through a report or dashboard to assist with case review ensuring access to helpful and accurate records. Adjudicators review the outputs of this use case, alongside other information and insights, to process a case and make a final determination. The adjudication process can be conducted without this tool, however, doing so would significantly increase the time and effort required to process immigration requests.
DHS-165	Automated Data Annotation	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2364	Anomaly Detection Homogenous Cargo	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2367	Computer Vision for Aerial Detection of Land and Open Water Items of Interest	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2369	AI for Software Delivery	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2371	Optical Counter - UAS Detection	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2377	Underwater ROV	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2378	Wellness and Physical Fitness Application	CBP	ai@hq.dhs.gov	d	c	\N
DHS-P2	AI for Autonomous Situational Awareness	CBP	ai@hq.dhs.gov	d	c	\N
DHS-2403	Security Operation Center (SOC) Network Anomaly Detection	CISA	ai@hq.dhs.gov	d	c	\N
DHS-5	Confidence Scoring for Cybersecurity Threat Indicators	CISA	ai@hq.dhs.gov	d	c	\N
DHS-406	Report Analysis and Archive System (RAAS)	CWMD	ai@hq.dhs.gov	d	c	\N
DHS-368	Commercial Generative AI for Text Generation (AI Chatbot)	DHS	ai@hq.dhs.gov	d	c	\N
DHS-369	Commercial Generative AI for Image Generation	DHS	ai@hq.dhs.gov	d	c	\N
DHS-373	Commercial Generative AI for Code Generation	DHS	ai@hq.dhs.gov	d	c	\N
DHS-2440	Recovery and Resilience Resource (RRR) Portal	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-2442	Digital Processing Procedure Manual (D-PPM)	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-248	Incident Management Workforce Deployment Model (depmod)	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-251	Individual Assistance (IA) & Public Assistance (PA) Projections	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-254	Planning Assistant for Resilient Communities (PARC)	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-346	Geospatial Damage Assessments	FEMA	ai@hq.dhs.gov	d	c	\N
DHS-53	Identification Card and Travel Document Code Detection	ICE	ai@hq.dhs.gov	d	c	\N
DHS-9	Machine Translation (Previously Language Translator)	ICE	ai@hq.dhs.gov	d	c	\N
DHS-2420	MiX MedINT (Medical Intelligence Dashboard and Canvas)	OHS	ai@hq.dhs.gov	d	c	\N
DHS-2395	Conversation Training and Feedback Simulator	TSA	ai@hq.dhs.gov	d	c	\N
DHS-17	Case Processing Improvements in FDNS-DS NexGen	USCIS	ai@hq.dhs.gov	d	c	\N
DHS-2544	OCR for Scanning and Cataloging Documentation [Captiva Open Text]	USCIS	ai@hq.dhs.gov	d	c	\N
DHS-185	Babel	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2380	Passive Body Scanner	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2388	CBP Translate	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2389	Passenger Security Assessment Model	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2390	Cargo Security Assessment Model	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2391	Illicit Trade	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2412	Supervised Traveler Identity Verification Services (Officer Initiated)	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2413	Semi-Supervised Traveler Identity Verification Services (Traveler Initiated)	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2414	3rd Party Traveler Identity Verification Services	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2415	Traveler Self-Service Mobile Identity Verification	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2416	Traveler Identity Verification Services (Vetting)	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2538	Open Source and Social Media Analysis	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2561	Cryptocurrency Analysis	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2570	Traffic Jam	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2619	CBP Link	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2669	Land Border Integration	CBP	ai@hq.dhs.gov	c	a	\N
DHS-2731	Mobile Fortify	CBP	ai@hq.dhs.gov	c	a	\N
DHS-315	ERNIE	CBP	ai@hq.dhs.gov	c	a	\N
DHS-398	Unified Processing/Mobile Intake	CBP	ai@hq.dhs.gov	c	a	\N
DHS-80	Traveler Entity Resolution	CBP	ai@hq.dhs.gov	c	a	\N
DHS-365	Consular Consolidated Database (CCD) Facial Recognition (FR) On Demand Report (VISA Only)	DHS	ai@hq.dhs.gov	c	a	\N
DHS-2408	Hurricane Score	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2457	Facial Recognition for Locating Vulnerable Populations	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2458	Facial Recognition for National Security Investigations	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2459	Facial Recognition for Investigations of Transnational Criminal Organizations	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2556	AI-Assisted Resume Screening Tool	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2577	Mobile Fortify	ICE	ai@hq.dhs.gov	c	a	\N
DHS-2666	License Plate Capture and Analysis	ICE	ai@hq.dhs.gov	c	a	\N
DHS-362	Facial Recognition for Investigations of Child Sexual Exploitation and Abuse	ICE	ai@hq.dhs.gov	c	a	\N
DHS-135	Low Probability of False Alarm (Low-Pfa) Algorithm for on-person screening.	TSA	ai@hq.dhs.gov	c	a	\N
DHS-327	Credential Authentication Technology with Camera System (CAT-2) and AutoCAT (CAT-2 in an e-gate form factor)	TSA	ai@hq.dhs.gov	c	a	\N
DHS-345	PreCheck Touchless Identity Solution	TSA	ai@hq.dhs.gov	c	a	\N
DHS-130	Text Analytics Data Science Sentence Similarity Model	USCIS	ai@hq.dhs.gov	c	a	\N
DHS-181	Automated Realtime Global Organization Specialist (ARGOS) for Company Registration Submissions to E-Verify	USCIS	ai@hq.dhs.gov	c	a	\N
DHS-2384	Verification Match Model	USCIS	ai@hq.dhs.gov	c	a	\N
DHS-413	I-765 - USCIS Facial Recognition through IDENT (1:1 Face Recognition/Validation)	USCIS	ai@hq.dhs.gov	c	a	\N
DHS-55	Person-Centric Identity Services Deduplication Model	USCIS	ai@hq.dhs.gov	c	a	\N
DHS-415	Criminal Investigations (OBIM)	USSS	ai@hq.dhs.gov	c	a	\N
DHS-101	The Advanced Trade Analytics Platform (ATAP)	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources. Additionally, the AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.
DHS-183	Public Information Compilation for Travel Threat Analysis (Dataminr)	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources. The AI output only provides the officer with complied public information.  The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.
DHS-188	Airship Outpost for Conveyance Identification	CBP	ai@hq.dhs.gov	c	b	The AI is not being used for tracking or analysis. It is simply identifying the alpha-numeric values of the conveyances in front of it.
DHS-2383	Unmanned Aircraft Collision Avoidance	CBP	ai@hq.dhs.gov	c	b	This use case avoids collisions for small unmanned aircraft systems. It operates a video feed that activates the obstacle avoidance features. The obstacle avoidance capability assists the pilot on the ground to avoid colliding the unmanned aircraft with objects such as man-made structures, vehicles, trees, wires, or other objects in the projected flight path. The pilot receives a visual alert on the hand controller, indicating a possible collision and in some cases the aircraft will slow down, change direction to avoid the obstacle, or stop.
DHS-24	Entity Resolution	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources. AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.
DHS-2417	Process Efficiency Traveler Identity for Airline Check-in and Bag Drop	CBP	ai@hq.dhs.gov	c	b	This is an option for travelers, not a requirement. If a traveler chooses to use it and the service cannot match a traveler, the traveler may continue check-in/bag drop via another means. CBP does not make any decision or action based on a no-match.
DHS-310	Customs Broker License Exam - Proctor Support	CBP	ai@hq.dhs.gov	c	b	This is not a high impact case because this would only be used in for examinees taking the Customs Broker License Exam and not used in requests for federal services, processes, and benefits to include loans and access to public housing. This is just a feature that the CBP exam vendor uses to detect cheating during the exam.
DHS-35	Autonomous Surveillance Tower	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. The AI provides alerts when it detects the presence of an IoI (i.e., persons, vehicles, animals) in the image frame. With regard to persons, this computer vision application is trained to determine if the object in the image frame is a person with a certain of level of confidence and not another object that may be shaped similarly to a person. After the alert of a detection, a trained agent or user, reviews the image to identify and classify the activity taking place. The AI merely alerts to the presence of an item it was trained to detect. This is not a biometric system and does not identify or track specific individuals.
DHS-37	Automated Item of Interest Detection	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. The AI runs on video and images captured from lawfully deployed technologies used to support the U.S. Border Patrol mission between Ports of Entry. The AI provides alerts when it detects the presence of an IoI, such as persons, vehicles, animals in the image frame. With regard to persons, this computer vision application is trained to determine if the object in the image frame is a person with a certain of level of confidence and not another object that may be shaped similarly to a person. After the alert of a detection, a trained agent or user, reviews the image to identify and classify the activity taking place. The AI merely alerts to the presence of an item it was trained to detect.
DHS-38	Vessel Detection	CBP	ai@hq.dhs.gov	c	b	The computer vision application scans a large grid within the viewshed of the high-definition camera. It then attempts to detect small vessels detecting entering and exiting small waterways in and around the area the camera is deployed.  System is calibrated to detect to identify inbound and outbound traffic.  When it detects a vessel it sends and image to the cloud for user review and determination if any follow-up action is required.  The AI output does not serve as a principal basis for decisions or actions related to the definition of High-Impact AI.
DHS-401	Vault Access Log (SPVAA)	CBP	ai@hq.dhs.gov	c	b	This use case uses facial recognition technology in Seized Property Vault Activity Automation (SPVAA) to create a log of access to a seized property vault. Photos of the CBP personnel accessing the vault are loaded into the application and logs the entrance request, the case number associated with the entrance request, and the individual’s access to the vault.
DHS-65	Aircraft Landing Location Predictor (KESTREL)	CBP	ai@hq.dhs.gov	c	b	The AI predicts aircraft landing locations.  The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources. The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.
DHS-81	Passport Anomaly Model	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. The AI output is an assessment of passport validity in response to an officer's request for passport validation. This result could be related to an inconsistency or abnormality in a passport's pattern. This is a tool available to CBP officers for confirming the validity of a passport. This result is used to notify the CBP officer that a passport may require review, as it may be part of a newly released sequence, may be invalid, or even possibly fraudulent. This is only one piece of information provided to CBP Officers during the normal course of their duties. The officers would use any results provided to research the validity of the passport through other sources.
DHS-86	Agriculture Commodity Model (AGC)	CBP	ai@hq.dhs.gov	c	b	The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources. The use case identifies agricultural pest risk in cargo shipments entering the United States. If a cargo shipment is identified as high-risk for pest infestation, it is prioritized for inspection. The model does not track or identify individuals.
DHS-95	Trade Entity Risk Model	CBP	ai@hq.dhs.gov	c	b	The Trade Entity Risk model/tool enhances cargo predictive threat models by providing a comprehensive risk profile that aggregates historical trade entity transactions, trading partner relationships, reviews, examinations, and violations (within CBP data holdings) to create quantifiable risk measures for all trade entities. The AI model serves as an input to larger AI/ML cargo risk targeting models to better assess cargo threats and inform focus areas for trade targeting. Its outputs are not directly shared with users or operators and the output does not serve as a principal basis for decision or actions.
DHS-125	Investigative Prioritization Aggregator	ICE	ai@hq.dhs.gov	c	b	This use case provides more efficient data processing for HSI personnel. The AI output may be used to produce investigative insights in the form of data, information leads or connections that HSI personnel can use to inform investigations, but the output itself is data preparation and organization so HSI personnel can produce those leads when combining the AI output with the personnel’s expertise and other relevant investigative data and information. Personnel may use these insights for law enforcement purposes in ongoing investigations with existing targets to assist in activities such as producing risk assessments about individuals or identifying criminal suspects; however, all insights are reviewed and validated by both personnel and supervisors before being included in any official case management system, and do not serve as a principal basis for law enforcement action or decision. Any enforcement decisions related to these insights are outcomes of the full Federal Investigation Process involving verifying any insights as evidence (including validating AI-translated material by a certified interpreter), presentation to a U.S. Attorney’s Office and potentially a District Court judge, decision to prosecute, judicial review, and trial and sentencing.
DHS-2427	Translation and Transcription for Investigative Data	ICE	ai@hq.dhs.gov	c	b	This use case provides more efficient data processing for HSI personnel. The AI output may be used to produce investigative insights in the form of data, information leads or connections that HSI personnel can use to inform investigations, but the output itself is data preparation and organization so HSI personnel can produce those leads when combining the AI output with the personnel’s expertise and other relevant investigative data and information. Personnel may use these insights for law enforcement purposes in ongoing investigations with existing targets to assist in activities such as producing risk assessments about individuals or identifying criminal suspects; however, all insights are reviewed and validated by both personnel and supervisors before being included in any official case management system, and do not serve as a principal basis for law enforcement action or decision. Any enforcement decisions related to these insights are outcomes of the full Federal Investigation Process involving verifying any insights as evidence (including validating AI-translated material by a certified interpreter), presentation to a U.S. Attorney’s Office and potentially a District Court judge, decision to prosecute, judicial review, and trial and sentencing.
DHS-2511	AI-Assisted Audio/Video Redaction	ICE	ai@hq.dhs.gov	c	b	The AI-Assisted Audio/Video Redaction use case does not meet the definition of a High-Impact category under OMB M-25-21 due to its narrowly defined scope, reliance on human oversight, and non-decision-making role. This tool is designed to assist Homeland Security Investigations (HSI) by partially automating the redaction of audio and video evidence, such as detecting and obscuring faces, objects, or sensitive information (e.g., license plates, PII), to protect individuals’ identities during investigations and legal proceedings. Importantly, the tool does not perform 1:1 facial matching or identification, and its outputs are strictly limited to redactions, which are subject to comprehensive human review and editing before finalization. This ensures that the AI’s role is supportive rather than determinative, with no direct impact on investigative decisions or legal outcomes.
DHS-2517	Dark Web Threat Intelligence for Cyber Investigations	ICE	ai@hq.dhs.gov	c	b	This use case provides a more efficient way to process, review, summarize, translate, and analyze dark web data for use in HSI investigations. The AI output may be used to produce investigative insights, but the output itself is supporting information for HSI personnel to use for ease of review, for further analysis, and to produce leads. Insights derived from translated data allow investigators to identify the most relevant data that, if deemed critical for court proceedings, can be submitted to certified human translators for final review. Personnel may use investigative insights for law enforcement actions such as identifying criminal suspects; however, all insights are reviewed and validated by both personnel and supervisors before being included in any official case management system, and do not serve as a principal basis for any law enforcement action or decision. Any enforcement decisions related to these insights are outcomes of the full Federal Investigation Process involving verifying any insights as evidence (including validating AI-translated material by a certified interpreter), presentation to a U.S. Attorney’s Office and potentially a District Court judge, decision to prosecute, judicial review, and trial and sentencing.
DHS-2547	Entity Resolution for Global Trade Data	ICE	ai@hq.dhs.gov	c	b	Although the use case falls into a presumed high-impact category related to law enforcement investigations, it does not meet the high-impact definition as its outputs do not directly serve as a principal basis for enforcement actions or regulatory decisions. Instead, the AI-generated knowledge graph provides a foundation for further human-led investigation, requiring source validation through separate processes. This delineation ensures that the AI output remains a supportive rather than a determinative factor, disqualifying it from the high-impact AI system category.
DHS-2575	Blockchain Analysis	ICE	ai@hq.dhs.gov	c	b	Despite falling into a presumed category of high-impact AI, this use case does not meet the definition because the AI’s outputs serve primarily as inputs to an investigative process rather than making legally binding or material decisions itself. HSI investigators review, validate, and contextualize the AI-generated outputs before integrating them into any official case management system. Enforcement decisions and outcomes arise from a full investigative process that includes judicial review and other safeguards, thereby distancing the AI outputs from direct impact on civil liberties or privacy
DHS-2578	Enhanced Lead Identification and Targeting	ICE	ai@hq.dhs.gov	c	b	While ELITE provides actionable data to ERO officers, its outputs are limited to normalized address data and do not serve as a principal basis for decisions or actions with legal, material, binding, or significant effects on individuals. ERO officers review and validate the AI-driven outputs before determining actions, ensuring human oversight and additional verification steps. Furthermore, enforcement decisions are based on the full investigative process, which includes human analysis and validation of the source of AI outputs. As such, the AI system's role is limited to data extraction and normalization, rather than serving as a primary basis for enforcement actions.
DHS-407	Biometric Check-in for ATD-ISAP (SmartLINK)	ICE	ai@hq.dhs.gov	c	b	Facial verification is only one option for check-in. If the remote check-in fails, either because it was unable to verify the match between the user and their previously taken photo, or because of other potential issues (poor lighting, camera/phone malfunction, etc...), an officer will manually review the check-in photo against the previously taken photos. If that fails, the user can schedule an in-person check-in at their local ERO office. Therefore, the output of AI (facial verification for a remote check-in) is not the primary basis for a decision or action that would affect the individual's rights or safety. It is a convenience to help save time for both the user and officers.
DHS-2434	User and Entity Behavior Analytics (UEBA)	MGMT	ai@hq.dhs.gov	c	b	The CVAS sub-system inside the VIEW system of record is not a high-impact use case because the Al's output from CVAS does not actually "serve as a principal basis for" the relevant type of agency action or decision. The collated information supports decisions about staffing priorities but is not used to make security-related or employment-related decisions. The use case also does not perform workplace monitoring or surveillance.
DHS-14	Biometrics Enrollment Tool (BET) Fingerprint Quality Check	USCIS	ai@hq.dhs.gov	c	b	The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. This tool simply identifies whether a fingerprint collected is of sufficient quality to pass the FBI fingerprint check process, ultimately maximizing the number of successful FBI submissions while minimizing the number of fingerprint recaptures necessary. This quality assurance step is one task in a series of adjudication activities but is not determinative of the overall adjudication decision. The tool saves personnel time and resources while enhancing customer experience by helping to ensure that only quality fingerprints are passed forward for matching against the FBI Identity History Summary Check. Results of FBI fingerprint checks are subsequently reviewed by a human as part of the immigration adjudicative process.
DHS-180	Automated Name and Date of Birth (DOB) Harvesting Service	USCIS	ai@hq.dhs.gov	c	b	The use case improves case processing efficiency by reducing the amount of time USCIS staff must spend to manually find aliases and dates of birth (DOBs) in existing records of an individual. The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. The use case increases efficiency of tasks associated with accurate and timely identification, analysis, and review of biographical information needed for adjudication. The AI outputs are suggested aliases and DOBs related to the individual query, which USCIS staff must review to accept, reject, or ignore the suggested information. The AI outputs reduce the amount of adjudicative time spent manually harvesting aliases and DOBs. The use case increases efficiency of tasks associated with reviewing existing records for adjudicating requests for immigration benefits. Completing such adjudications are not dependent on the use case however lack of this tool would significantly increase human processing times and potentially reduce the accuracy of information consulted during the human review process.
DHS-189	ELIS Card Photo Validation Service	USCIS	ai@hq.dhs.gov	c	b	This use case supports beneficiaries submitting an e-filed I-765 via myUSCIS to apply for employment authorization. These applications include a digital ID photo of the applicant, which will be printed on their Employment Authorization Document (EAD) card if the application is accepted. The use case determines whether a user-uploaded ID photo is suitable for use on an EAD card, and notifies the submitter if it detects a potential quality issue with the photo. (SEE DHS CAIO SUPER MEMO FY24)   ---  The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.  The AI outputs are a real-time advisory message to the submitter of the photo that it is of insufficient quality for card production at which point the submitter may choose to resubmit or not. While adjudication of EADs is not dependent on this use case, this tool enhances efficiency and customer service by minimizing the number of cards failing in production and delays related to subsequent requests for information.  (SEE USCIS REQUEST FOR DHS CAIO DETERMINATION FY24)
DHS-2543	AI Security and Monitoring	USCIS	ai@hq.dhs.gov	c	b	This use case collates information provided by or authorized to be collected by an employee as part of network security process. The collated information supports decisions about staffing priorities but is not used to make security-related or employment-related decisions.
DHS-372	User Entity and Behavior Analytics (UEBA) for Security Operations (SecOps) Anomaly Identification	USCIS	ai@hq.dhs.gov	c	b	This use case collates information provided by or authorized to be collected by an employee as part of network security process. The collated information supports decisions about staffing priorities but is not used to make security-related or employment-related decisions.
DHS-56	Person-Centric Identity Services Information Compilation Check	USCIS	ai@hq.dhs.gov	c	b	This use case verifies the ongoing accuracy of information compiled from within the Person-Centric Identity Services (PCIS). It identifies which records from within PCIS best match search criteria to support case processing.  ------  The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services.  The use case compiles records from across a variety of USCIS systems to provide a comprehensive history of a person’s interaction with USCIS. The output of this can be visualized through a report or dashboard to assist with case review ensuring access to helpful and accurate records. Adjudicators review the outputs of this use case, alongside other information and insights, to process a case and make a final determination. The adjudication process can be conducted without this tool, however, doing so would significantly increase the time and effort required to process immigration requests.
DHS-2366	CBP Careers Bot - Leo	CBP	ai@hq.dhs.gov	c	c	\N
DHS-2373	CBP Employee Experience	CBP	ai@hq.dhs.gov	c	c	\N
DHS-2451	Position Description Generation and Evaluation	CBP	ai@hq.dhs.gov	c	c	\N
DHS-2529	Global Entry Mobile App Traveler AI Question Answering Service	CBP	ai@hq.dhs.gov	c	c	\N
DHS-2530	ChatCBP	CBP	ai@hq.dhs.gov	c	c	\N
DHS-2704	GenAI for Document Summarization and Content Generation	CBP	ai@hq.dhs.gov	c	c	\N
DHS-399	Cyber Threat Analysis (Recorded Future)	CBP	ai@hq.dhs.gov	c	c	\N
DHS-68	Empty Container Detection Model (Cargo Insights Team)	CBP	ai@hq.dhs.gov	c	c	\N
DHS-69	Commodity Detection Model (Cargo Insights Team)	CBP	ai@hq.dhs.gov	c	c	\N
DHS-94	Cargo Classification Tool	CBP	ai@hq.dhs.gov	c	c	\N
DHS-106	Critical Infrastructure Network Anomaly Detection	CISA	ai@hq.dhs.gov	c	c	\N
DHS-2306	CISAChat	CISA	ai@hq.dhs.gov	c	c	\N
DHS-4	Automated Detection of Personally Identifiable Information (PII) in Cybersecurity Data	CISA	ai@hq.dhs.gov	c	c	\N
DHS-2296	OCFO Response Augmentation Suite	FEMA	ai@hq.dhs.gov	c	c	\N
DHS-2441	OCFO Code Assist GPT	FEMA	ai@hq.dhs.gov	c	c	\N
DHS-2710	Executive Summary GPT	FEMA	ai@hq.dhs.gov	c	c	\N
DHS-2720	Public Assistance Workload Projections	FEMA	ai@hq.dhs.gov	c	c	\N
DHS-2722	Individual Assistance (IA) Predictive Models for Program Quantities	FEMA	ai@hq.dhs.gov	c	c	\N
DHS-2424	AI Assisted Compromise Email Detector (AACED)	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2425	Intelligent Document Processing	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2426	Cybersecurity Threat Management, Detection, and Response	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2515	AI-Enhanced ICE Tip Processing	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2553	Media Classifier for Computer and Digital Storage Evidence	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2758	AI-Powered Developer Tools	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2759	Open-Source Intelligence for Investigations	ICE	ai@hq.dhs.gov	c	c	\N
DHS-P1	Normalization Services	ICE	ai@hq.dhs.gov	c	c	\N
DHS-2433	DHS-Chat	MGMT	ai@hq.dhs.gov	c	c	\N
DHS-2453	ESEC Inquiry (STORM) Summarization	MGMT	ai@hq.dhs.gov	c	c	\N
DHS-419	AdaptiveMFA	MGMT	ai@hq.dhs.gov	c	c	\N
DHS-45	Text Analytics for Survey Responses (TASR)	MGMT	ai@hq.dhs.gov	c	c	\N
DHS-2432	Airport Throughput Predictive Model	TSA	ai@hq.dhs.gov	c	c	\N
DHS-2518	Geographic Current Events Real-Time Alerting Tool	TSA	ai@hq.dhs.gov	c	c	\N
DHS-2522	idiCORE Subscriptions	TSA	ai@hq.dhs.gov	c	c	\N
DHS-2604	AskTSA	TSA	ai@hq.dhs.gov	c	c	\N
DHS-2605	Lexis Nexis	TSA	ai@hq.dhs.gov	c	c	\N
DHS-2609	 SITE Group Subscription Services	TSA	ai@hq.dhs.gov	c	c	\N
DHS-178	Adaptive Risk Model for Inspected Small Passenger Vessels	USCG	ai@hq.dhs.gov	c	c	\N
DHS-16	ELIS Evidence Classifier Service	USCIS	ai@hq.dhs.gov	c	c	\N
DHS-2385	Intelligent Document Processing (IDP) for I-539 Form Digitization	USCIS	ai@hq.dhs.gov	c	c	\N
DHS-2598	PDF Intake (PDFI) for myUSCIS	USCIS	ai@hq.dhs.gov	c	c	\N
DHS-366	AI Interview Simulator for Officer Training	USCIS	ai@hq.dhs.gov	c	c	\N
DHS-2626	License Plate Reader 	USSS	ai@hq.dhs.gov	c	c	\N
DHS-2745	FLIR 280 HD	USCG	ai@hq.dhs.gov	b	a	\N
DHS-2572	Acoustic Signature AI for Gunshot Detection	CBP	ai@hq.dhs.gov	b	b	This system detects sounds that are associated with sounds of gunfire. Only events classified as High Confidence are then sent to users as a detection. Users then review the audio of the event to determine the accuracy of the detection and to review the location of the detection on an associated map. If the audio review is deemed relevant by agent and/or system users, agents may be sent to investigate further and the message is sent to field personnel of potential gunshot activity. It may be warning of activity south of the border where notifications made enhance safety of officers/agents in the region.  Any further actions taken will be based on what the agents encounter when they arrive on scene. The AI associated with this system is not a principle basis for a decision or action.
DHS-2729	Facial Recognition for National Security and Transnational Criminal Organizations	CBP	ai@hq.dhs.gov	b	b	The AI utilizes publicly available images and performs a comparative search against other open-source images to identify potential matches. Results produced by the AI can only be utilized for investigative leads and cannot be utilized as a determining factor for any enforcement action by CBP personnel. Therefore, in instances where the AI outputs assist in identifying leads, CBP personnel must then use internal CBP or USG data prior to making any law enforcement decisions or actions. The outputs of the AI do not serve as the principal basis for a high-impact decision or action.
DHS-163	Non-Intrusive Inspection (NII) 3D Imaging Tool	CBP	ai@hq.dhs.gov	b	c	\N
DHS-2439	Hazard Mitigation Assistance Chatbot	FEMA	ai@hq.dhs.gov	b	c	\N
DHS-2711	Technical Resource for Mitigation Programs	FEMA	ai@hq.dhs.gov	b	c	\N
DHS-2727	Large Language Model (LLM) Guided Data Dictionary Generation	FEMA	ai@hq.dhs.gov	b	c	\N
DHS-2454	LIGER Generative AI Toolkit	MGMT	ai@hq.dhs.gov	b	c	\N
DHS-2705	Smartphone Information Forensics Triage	CBP	ai@hq.dhs.gov	a	a	\N
DHS-313	Advanced Analytics for X-ray Images (AAXI)	CBP	ai@hq.dhs.gov	a	a	\N
DHS-314	Advance RPM Maintenance Operating Reporter (ARMOR)	CBP	ai@hq.dhs.gov	a	a	\N
DHS-2721	AI Resume & ATS App	FEMA	ai@hq.dhs.gov	a	a	\N
DHS-2749	Real-Time Language Translation Services	ICE	ai@hq.dhs.gov	a	a	\N
DHS-131	Automated Target Recognition (ATR) Developments for Standard Screening	TSA	ai@hq.dhs.gov	a	a	\N
DHS-132	Accessible Property Screening (APS) Checkpoint CT Prohibited Items (PI) Detection	TSA	ai@hq.dhs.gov	a	a	\N
DHS-133	Walk-Through Metal Detector (WTMD) Alternative Automated Target Recognition (ATR) Developments	TSA	ai@hq.dhs.gov	a	a	\N
DHS-134	Synthetic data for improved Automated Threat Recognition (ATR) in checkpoint screening	TSA	ai@hq.dhs.gov	a	a	\N
DHS-2399	Electronic Evidence/Video Recording Transcription and Summarization Tool	TSA	ai@hq.dhs.gov	a	a	\N
DHS-2305	USCIS Document Translation Service	USCIS	ai@hq.dhs.gov	a	a	\N
DHS-2514	USCIS Speech Translation Service	USCIS	ai@hq.dhs.gov	a	a	\N
DHS-194	AI Enabled Autonomous Underwater Vehicle	CBP	ai@hq.dhs.gov	a	b	Computer Vision application onboard the ROV detects items of interest (IoI).  The ROV also uses AI for collision avoidance. Once an IOI is detected, a bounding box is placed around the suspected IoI in the image and the user is notified of an alert of a potential IOI.  The user then reviews the image and decides if a dive team is required for further inspection. The AI output does not serve as a principal basis for any decisions or actions.
DHS-234	Relocatable Multi-Sensor System	CBP	ai@hq.dhs.gov	a	b	Sensors and CUAS capabilities to support significant events. The AI combines sensor data from RF detections / radar/ and infrared / electro optical cameras.  It combines all feeds and provides detections on the user interface back to users. Fully standalone and airgapped system. Looking to identify non-RF drones. System does not have any mitigation capability, system cannot autonomously mitigate an aircraft, it only detects and provides a digital track on the GUI/map for further user investigation. This use of AI does not serve as a principal basis for decision or action.
DHS-2363	Anomaly Detection COV Structure	CBP	ai@hq.dhs.gov	a	b	Computer Vision is intended to detect anomalies in non-intrusive inspection images. The images are then shared with officers who review the detections within the images (represented as a polygon). If the officer feels physical review is required, the vehicle is moved to secondary inspection for more thorough review by an officer. The output of the AI does not serve as a principal basis for a decision or action.
DHS-2365	Anomaly Detection POV Structure	CBP	ai@hq.dhs.gov	a	b	Computer Vision is intended to detect anomalies in non-intrusive inspection images. The images are then shared with officers who review the detections within the images (represented as a polygon). If the officer feels physical review is required, the vehicle is moved to secondary inspection for more thorough review by an officer. The output of the AI does not serve as a principal basis for a decision or action.
DHS-2565	CBP Common AI Service(CCAIS) Image Analysis and Data Correlation	CBP	ai@hq.dhs.gov	a	b	This use case is not yet live in production, and the current ATT only covers for within the CCAIS platform.  The use case needs further review, prior to the ATT for ICAD integration.  The model can identify people, animals, and vehicles as well as extract license plate information, and we will need to determine how exactly the extracted information will be used for operations if it is determined to be feasible.  The AI inventory team will need to review once the AI Use Case is fully defined.
DHS-2568	Non-intrusive vessel and object detection tool (Tethered Aerostat Radar System (TARS))	CBP	ai@hq.dhs.gov	a	b	The AI will analyze images from the sensors to determine what the item is in the image (e.g. Vessel).  The image location will also be correlated with any publicly available AIS (Automated Identified System) data for maritime traffic. AIS is used as a filtering mechanism in most cases to filter out legitimate traffic.  User is provided with information for detected objects lacking AIS signal. After the alert of a detection, a trained CBP agent or user, reviews the image to identify and classify the activity taking place. This use of AI does not serve as the principal basis for decisions or actions.
DHS-317	RAPTOR (Rapid Tactical Operations Reconnaissance)	CBP	ai@hq.dhs.gov	a	b	The AI system processes data from radar, infrared sensors, and video surveillance to detect and track suspicious activities along U.S. borders. By incorporating AI-powered vessel registration, aircraft tail number, license plate, and object detection RAPTOR significantly boosts domain awareness. If the OCR can capture vessel or license plate information, that information is run through CBP Super Query and if derogatory information is returned or other information from the imagery (high number of gas cans in the image) the information is sent through SMS or email to the field for response to the potential activity. Agents log into RAPTOR and reviews for accuracy/validity of image to avoid any investigation of the wrong boat.  Neither the AI or output of AI serves as a principal basis for a decision or action. Human review takes place prior to any final decision to act, and then personal interaction leads to any follow-up decisions.
DHS-204	Semantic Search and Summarization for Investigative Data	ICE	ai@hq.dhs.gov	a	b	This use case provides a natural language contextual search and summarization capability against existing Reports of Investigation and other investigative data, producing more relevant search responses and investigative insights in the form of data, information leads or connections that HSI personnel can use to inform investigations. The AI output (search queries and responses) provide investigators with easy-to-read search responses that are accompanied by links to source material for further analysis. Any data used to produce these investigative insights are first obtained through legal means and processes for the purposes of law enforcement investigations and do not significantly impact the categories listed in the definitions of “high-impacting AI.” Personnel may use these insights for law enforcement purposes in ongoing investigations with existing targets to assist in activities such as producing risk assessments about individuals or identifying criminal suspects; however, all insights are reviewed and validated by both personnel and supervisors before being included in any official case management system, and do not serve as a principal basis for enforcement decisions. Any enforcement decisions related to these insights are outcomes of the full Federal Investigation Process involving verifying any insights as evidence.
DHS-2552	Mobile Device Forensics for Investigations	ICE	ai@hq.dhs.gov	a	b	This use case falls into a presumptive high-impact category under M-25-21 Section 6 (j) due to its role in supporting law enforcement activities, specifically application of digital forensic techniques. However, it does not meet the definition of high-impact AI as outlined in OMB Memorandum M-25-21 because its outputs do not serve as a "principal basis" for decisions or actions with legal, material, binding, or significant effects on an individual or entity's civil rights, civil liberties, or privacy; or human health and safety. The AI capabilities, including classification, decoding, and origin analysis, are designed to assist analysts in prioritizing human review rather than independently determining outcomes. For example, AI-generated tags and app artifacts are suggestions that require manual validation and further investigation before enforcement actions are taken. All outputs are reviewed as part of a broader investigative process before any actions are taken.
DHS-2595	Open-Source Intelligence for Lead Identification and Targeting	ICE	ai@hq.dhs.gov	a	b	This use case falls into a presumptive high-impact category due to its role in supporting law enforcement activities, specifically in identifying individuals who pose risks to community safety or violate U.S. immigration laws. However, it does not meet the definition of high-impact AI as outlined in OMB Memorandum M-25-21 because its outputs do not serve as a "principal basis" for decisions or actions with legal, material, binding, or significant effects on an individual or entity's civil rights, civil liberties, or privacy; or human health and safety. The AI modules, including risk extraction, image analysis, language detection, and AI chat, are designed to augment traditional investigative processes by providing structured annotations and insights for analysts to review. These outputs are explicitly described as supporting tools that require human validation and integration with other government data holdings before any enforcement action is taken. Furthermore, the AI system operates as a supplementary tool, consolidating and organizing information to enhance efficiency, but does not independently produce outcomes that directly affect civil rights, civil liberties, or privacy. The safeguards in place, including human validation and adherence to established legal standards, ensure that the AI outputs remain supportive rather than determinative, confirming that this use case does not meet the high-impact definition.
DHS-2667	Global Maritime Intelligence	ICE	ai@hq.dhs.gov	a	b	This use case does not meet the definition of "high-impact" as outlined in Section 5 of M-25-21 because its outputs do not serve as a "principal basis for decisions or actions that have a legal, material, binding, or significant effect on rights or safety." Instead, the AI system generates intelligence reports and risk assessments that are used to support human decision-making. Analysts review the outputs and initiate follow-on actions after validating the source data, such as inspections or investigations, ensuring that the AI's outputs are not the sole or principal basis for these decisions.   While the use case aligns with a presumed high-impact category due to its critical role in maritime safety and law enforcement, it does not meet the stricter definition of high-impact because its outputs are advisory and produce leads that must be validated as part of the investigative process prior to action being taken.
DHS-48	Email Analytics for Investigative Data	ICE	ai@hq.dhs.gov	a	b	This use case provides more efficient data processing for HSI personnel. The AI output may be used to produce investigative insights in the form of data, information leads or connections that HSI personnel can use to inform investigations, but the output itself is data preparation and organization so HSI personnel can produce those leads when combining the AI output with the personnel’s expertise and other relevant investigative data and information. Personnel may use these insights for law enforcement purposes in ongoing investigations with existing targets to assist in activities such as producing risk assessments about individuals or identifying criminal suspects; however, all insights are reviewed and validated by both personnel and supervisors before being included in any official case management system, and do not serve as a principal basis for law enforcement action or decision. Any enforcement decisions related to these insights are outcomes of the full Federal Investigation Process involving verifying any insights as evidence (including validating AI-translated material by a certified interpreter), presentation to a U.S. Attorney’s Office and potentially a District Court judge, decision to prosecute, judicial review, and trial and sentencing.
DHS-417	Machine Learning Analysis Applied to Cyber Threat Hunt Data	TSA	ai@hq.dhs.gov	a	b	The AI outputs do not produce an action or serve as a principal basis for a decision that has the potential to significantly impact the safety of human-life or well-being, climate or environment, critical infrastructure, or strategic assets or resources.  This use case detects anomalies or outliers, and also may be used to classify or categorize certain activity within data that has already been collected during an authorized cyber threat hunt operation within TSA’s networks. The AI outputs are reviewed by a human analyst team to determine if any of the patterns might be associated with unusual activity. The analyst would then continue to investigate further as during normal threat hunt operations.
DHS-2627	Extended Automated Name Harvesting (eANH)	USCIS	ai@hq.dhs.gov	a	b	No. The AI outputs do not serve as a principal basis for a decision or action concerning a specific individual or entity that has a legal, material, binding, or similarly significant effect on that individual’s or entity’s civil rights, civil liberties or privacy, equal opportunities, or access to or the ability to apply for critical government resources or services. The use case increases efficiency of tasks associated with the accurate and timely identification, analysis, and review of biographical information needed for adjudication.  The AI outputs are suggested aliases and DOBs related to the individual query, which USCIS staff must review to accept, reject, or ignore the suggested information. The AI outputs reduce the amount of adjudicative time spent manually harvesting aliases and DOBs. The use case increases efficiency of tasks associated with reviewing existing records for adjudicating requests for immigration benefits. Completing such adjudications are not dependent on the use case however lack of this tool would significantly increase human processing times and potentially reduce the accuracy of information consulted during the human review process.
DHS-2362	AI to generate testable synthetic data	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2375	Thermal Power Generation with Geoseismic IoI Detection and Classification	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2444	API Security Vulnerability Technology	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2446	Cyber Threat Detection	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2447	Forced Labor Virtual Consultant	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2449	Multi-media Insight Tool	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2452	Source Code Development Tool	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2540	Open Metadata	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2551	Automated Incident Creation (IT)	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2566	TRM Classification Tool	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2567	FOIA processing automated redaction (RedactAI)	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2569	Speech Assist Virtual Interview Assistant	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2571	Business Automation and Improved Search Ability with AI	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2586	CodeGen	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2587	CounselAI	CBP	ai@hq.dhs.gov	a	c	\N
DHS-2663	Border Infrastructure Center of Excellence AI (BICE AI)	CBP	ai@hq.dhs.gov	a	c	\N
DHS-311	Integrated Defense and Security Solutions (IDSS)	CBP	ai@hq.dhs.gov	a	c	\N
DHS-107	Malware Reverse Engineering	CISA	ai@hq.dhs.gov	a	c	\N
DHS-2335	Draft Tailored Summaries of Media Materials for Different Publication Channels	CISA	ai@hq.dhs.gov	a	c	\N
DHS-2709	Spend Plan Analysis GPT	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2712	Administrative & Productivity Support for IRC Resource Library	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2713	Individual Assistance Document Translation	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2717	Grants Manager Artificial Intelligence ChatBot	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2718	RTPD Division Services Desktop Automation	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2724	Program Integrity (RRAD-PI) AI Counter-Fraud Enhancement Measures	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-2726	Semantic Search, Summarization, and Data/Spatial Visualization for NCR Watch COP/Dashboard	FEMA	ai@hq.dhs.gov	a	c	\N
DHS-206	Title III Semantic Search and Summarization for Translated Content	ICE	ai@hq.dhs.gov	a	c	\N
DHS-208	Policy Analyst Assistant	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2402	SEVP Response Center Chatbot - SID (SEVIS Interactive Dialog)	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2423	Digital Records Manager (DRM) User Assistance Chatbot	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2436	Burlington Finance Center Voice Bot	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2467	Purchase Card Worksheet Analysis	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2513	Natural Language Search for Legal Case Management	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2559	Duplicate Contract Detection in Contract Tracking Application	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2581	Semantic Search for Digital Forensics Data	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2583	Draft Report Generation and Formatting for Investigations	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2584	Named Entity Resolution for Investigative Data	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2594	ICE Enterprise AI Assistant	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2603	ICE Terminology and Data Asset Discovery Chatbot	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2755	AI-Assisted eDiscovery Search	ICE	ai@hq.dhs.gov	a	c	\N
DHS-2342	JES and Appropriations Insight	MGMT	ai@hq.dhs.gov	a	c	\N
DHS-2343	CFO Navigator	MGMT	ai@hq.dhs.gov	a	c	\N
DHS-2406	DHS Asset Assessment Tool	MGMT	ai@hq.dhs.gov	a	c	\N
DHS-418	Spending Analysis and Budget Execution Risk (SABER) Model	MGMT	ai@hq.dhs.gov	a	c	\N
DHS-2418	MiX Phenotyping	OHS	ai@hq.dhs.gov	a	c	\N
DHS-2419	MiX Indicators	OHS	ai@hq.dhs.gov	a	c	\N
DHS-2421	One Health Threat Detection and Risk Assessment Platform (OH-TREADS) / Planner	OHS	ai@hq.dhs.gov	a	c	\N
DHS-2397	OTA Automated Passenger Screening Gate System	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2400	Answer Engine	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2428	Contract Requirement Automation	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2429	TSA Case Handling Platform	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2430	Automated Field Data Collection	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2431	Plan of Day Staff Optimization	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2526	Document Translation Service (DTS)	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2622	Service Now Predictive Intelligence Tool	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2676	Text Extraction from Uploaded Images	TSA	ai@hq.dhs.gov	a	c	\N
DHS-374	TSA Contact Center Virtual Assistant	TSA	ai@hq.dhs.gov	a	c	\N
DHS-2740	Risk Management Framework (RMF) Automation	USCG	ai@hq.dhs.gov	a	c	\N
DHS-2386	Sentiment Analysis -FOD Field Offices Complaints and Reviews	USCIS	ai@hq.dhs.gov	a	c	\N
DHS-2599	Private Artificial Intelligence (AI) Tech Hub (PAiTH)	USCIS	ai@hq.dhs.gov	a	c	\N
DHS-2641	Enterprise WiFi 	USSS	ai@hq.dhs.gov	a	c	\N
\.
